// src/services/mockData.ts
import type { VulnerabilityAssessment } from '../types/api';
import { VulnerabilityAssessmentType as VulnType, AssessmentStatus } from '../types/api';

export const mockAssessments: VulnerabilityAssessment[] = [
  {
    id: 1,
    title: 'Анализ сетевых уязвимостей',
    short_description: 'Комплексный анализ сетевой инфраструктуры',
    description: 'Проведение комплексного анализа сетевой инфраструктуры организации с целью выявления уязвимостей. Включает сканирование портов, анализ сетевых протоколов, проверку конфигурации сетевого оборудования и анализ политик безопасности. Результаты предоставляются в виде детального отчета с рекомендациями по устранению выявленных проблем.',
    price: 50000,
    impact_level: 2,
    assessment_type: VulnType.NETWORK_SCAN,
    status: AssessmentStatus.AVAILABLE,
    image_url: undefined,
  },
  {
    id: 2,
    title: 'Тестирование веб-приложений',
    short_description: 'Поиск уязвимостей в веб-приложениях',
    description: 'Профессиональное тестирование безопасности веб-приложений. Включает проверку на SQL-инъекции, XSS, CSRF, небезопасную аутентификацию и авторизацию. Анализ логики приложения, тестирование API, проверка на утечку конфиденциальной информации. Предоставляется подробный отчет с примерами эксплуатации и рекомендациями по исправлению.',
    price: 75000,
    impact_level: 3,
    assessment_type: VulnType.WEB_APP_PENTEST,
    status: AssessmentStatus.AVAILABLE,
    image_url: undefined,
  },
  {
    id: 3,
    title: 'Аудит инфраструктуры',
    short_description: 'Полный аудит IT-инфраструктуры',
    description: 'Комплексный аудит всей IT-инфраструктуры предприятия. Включает анализ серверной инфраструктуры, систем хранения данных, виртуализации, облачных сервисов. Проверка соответствия стандартам безопасности, анализ конфигураций, оценка рисков. Формирование стратегии повышения уровня информационной безопасности организации.',
    price: 120000,
    impact_level: 3,
    assessment_type: VulnType.INFRASTRUCTURE_AUDIT,
    status: AssessmentStatus.AVAILABLE,
    image_url: undefined,
  },
  {
    id: 4,
    title: 'Базовое сканирование периметра',
    short_description: 'Быстрая оценка внешнего периметра',
    description: 'Автоматизированное сканирование внешнего периметра сети организации с использованием профессиональных инструментов. Выявление открытых портов, запущенных сервисов, устаревших версий программного обеспечения. Быстрая оценка уровня защищенности внешних ресурсов компании. Идеально подходит для регулярного мониторинга состояния безопасности.',
    price: 35000,
    impact_level: 1,
    assessment_type: VulnType.NETWORK_SCAN,
    status: AssessmentStatus.AVAILABLE,
    image_url: undefined,
  },
  {
    id: 5,
    title: 'Углубленный пентест API',
    short_description: 'Детальный анализ безопасности API',
    description: 'Глубокое тестирование безопасности REST и GraphQL API. Проверка аутентификации и авторизации, анализ rate limiting, тестирование на инъекции, проверка логики бизнес-процессов через API. Тестирование документации API на предмет утечек информации. Анализ возможных векторов атак через API endpoints с детальными рекомендациями по защите.',
    price: 85000,
    impact_level: 3,
    assessment_type: VulnType.WEB_APP_PENTEST,
    status: AssessmentStatus.AVAILABLE,
    image_url: undefined,
  },
  {
    id: 6,
    title: 'Аудит Active Directory',
    short_description: 'Проверка безопасности доменной инфраструктуры',
    description: 'Комплексный аудит безопасности доменной инфраструктуры Active Directory. Проверка политик безопасности, анализ прав пользователей и групп, поиск неправильных конфигураций. Выявление потенциальных путей повышения привилегий, анализ GPO, проверка на наличие устаревших протоколов. Детальные рекомендации по усилению безопасности доменной среды.',
    price: 95000,
    impact_level: 2,
    assessment_type: VulnType.INFRASTRUCTURE_AUDIT,
    status: AssessmentStatus.AVAILABLE,
    image_url: undefined,
  },
];
