"""rename_fields_for_m2m

Revision ID: 196256d62caa
Revises: 40e630eac72b
Create Date: 2025-10-07 23:16:44.220997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196256d62caa'
down_revision: Union[str, Sequence[str], None] = '40e630eac72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    op.add_column('assessment_components', sa.Column('vulnerability_id', sa.Integer(), nullable=True))
    op.add_column('assessment_components', sa.Column('report_id', sa.Integer(), nullable=True))
    
    # Populate new columns with values from old columns
    op.execute("UPDATE assessment_components SET vulnerability_id = service_id, report_id = order_id")
    
    # Drop the old foreign key constraints
    op.drop_constraint(op.f('assessment_components_order_id_fkey'), 'assessment_components', type_='foreignkey')
    op.drop_constraint(op.f('assessment_components_service_id_fkey'), 'assessment_components', type_='foreignkey')
    
    # Add the new foreign key constraints
    op.create_foreign_key(None, 'assessment_components', 'assessment_reports', ['report_id'], ['id'])
    op.create_foreign_key(None, 'assessment_components', 'vulnerability_assessments', ['vulnerability_id'], ['id'])
    
    # Now that data is populated, we can make the columns NOT NULL
    op.alter_column('assessment_components', 'vulnerability_id', nullable=False)
    op.alter_column('assessment_components', 'report_id', nullable=False)
    
    # Drop the old columns
    op.drop_column('assessment_components', 'order_id')
    op.drop_column('assessment_components', 'service_id')
    
    # Alter the total_cost column in assessment_reports
    op.alter_column('assessment_reports', 'total_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_reports', 'total_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('assessment_components', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assessment_components', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assessment_components', type_='foreignkey')
    op.drop_constraint(None, 'assessment_components', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_components_service_id_fkey'), 'assessment_components', 'vulnerability_assessments', ['service_id'], ['id'])
    op.create_foreign_key(op.f('assessment_components_order_id_fkey'), 'assessment_components', 'assessment_reports', ['order_id'], ['id'])
    op.drop_column('assessment_components', 'report_id')
    op.drop_column('assessment_components', 'vulnerability_id')
    # ### end Alembic commands ###
