"""Add risk matrix fields

Revision ID: 313bb5d01b0b
Revises: bf560c80e10a
Create Date: 2025-09-22 18:15:24.371471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '313bb5d01b0b'
down_revision: Union[str, Sequence[str], None] = 'bf560c80e10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('parameters_and_comments', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.drop_column('orders_services', 'scan_parameters')
    op.drop_column('orders_services', 'report_url')
    op.add_column('services', sa.Column('impact_level', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'impact_level')
    op.add_column('orders_services', sa.Column('report_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('orders_services', sa.Column('scan_parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('orders', 'risk_score')
    op.drop_column('orders', 'parameters_and_comments')
    # ### end Alembic commands ###
