"""rename_models

Revision ID: 40e630eac72b
Revises: cebc41412586
Create Date: 2025-10-05 23:18:30.629798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40e630eac72b'
down_revision: Union[str, Sequence[str], None] = 'cebc41412586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerability_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('deleted', 'available', name='assessmentstatus'), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('impact_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('assessment_type', sa.Enum('NETWORK_SCAN', 'WEB_APP_PENTEST', 'INFRASTRUCTURE_AUDIT', name='vulnerabilityassessmenttype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'deleted', 'formed', 'completed', 'cancelled', name='reportstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('formation_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('target_system_info', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_draft_report', 'assessment_reports', ['created_by', 'status'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    # Define the enum using postgresql.ENUM to reference the existing type
    protection_level_enum = postgresql.ENUM('none', 'basic', 'full', name='protectionlevel', create_type=False)
    
    op.create_table('assessment_components',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('price_at_order_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protection_level', protection_level_enum, nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['assessment_reports.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['vulnerability_assessments.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'order_id')
    )
    op.drop_table('orders_services')
    op.drop_index(op.f('uq_user_draft_order'), table_name='orders', postgresql_where="(status = 'draft'::orderstatus)")
    op.drop_table('orders')
    op.drop_table('services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('services_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('deleted', 'available', name='servicestatus'), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('assessment_type', postgresql.ENUM('NETWORK_SCAN', 'WEB_APP_PENTEST', 'INFRASTRUCTURE_AUDIT', name='serviceassessmenttype'), autoincrement=False, nullable=False),
    sa.Column('impact_level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='services_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('orders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'deleted', 'formed', 'completed', 'cancelled', name='orderstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('formation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('moderated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_system_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='orders_created_by_fkey'),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], name='orders_moderated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('uq_user_draft_order'), 'orders', ['created_by', 'status'], unique=True, postgresql_where="(status = 'draft'::orderstatus)")
    op.create_table('orders_services',
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_at_order_time', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('protection_level', postgresql.ENUM('none', 'basic', 'full', name='protectionlevel'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('orders_services_order_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('orders_services_service_id_fkey')),
    sa.PrimaryKeyConstraint('service_id', 'order_id', name=op.f('orders_services_pkey'))
    )
    op.drop_table('assessment_components')
    op.drop_index('uq_user_draft_report', table_name='assessment_reports', postgresql_where=sa.text("status = 'draft'"))
    op.drop_table('assessment_reports')
    op.drop_table('vulnerability_assessments')
    # ### end Alembic commands ###
