"""Added short description to service

Revision ID: 6f288137a77f
Revises: 313bb5d01b0b
Create Date: 2025-09-22 18:28:42.461217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f288137a77f'
down_revision: Union[str, Sequence[str], None] = '313bb5d01b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('short_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'short_description')
    # ### end Alembic commands ###
