"""Initial migration with all tables

Revision ID: bf560c80e10a
Revises: 
Create Date: 2025-09-18 16:58:18.502513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf560c80e10a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('deleted', 'available', name='servicestatus'), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('assessment_type', sa.Enum('NETWORK_SCAN', 'WEB_APP_PENTEST', 'INFRASTRUCTURE_AUDIT', name='serviceassessmenttype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_moderator', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'deleted', 'formed', 'completed', 'cancelled', name='orderstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('formation_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('target_system_info', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_draft_order', 'orders', ['created_by', 'status'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_table('orders_services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('price_at_order_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scan_parameters', sa.JSON(), nullable=True),
    sa.Column('report_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_services')
    op.drop_index('uq_user_draft_order', table_name='orders', postgresql_where=sa.text("status = 'draft'"))
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
