# alembic/versions/cebc41412586_refactor_risk_calculation_to_m2m_table.py

"""Refactor risk calculation to m2m table

Revision ID: cebc41412586
Revises: <предыдущая_ревизия>
Create Date: <дата_создания>
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebc41412586'
down_revision: Union[str, None] = '6f288137a77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- ИСПРАВЛЕНИЕ 1: Определяем наш Enum тип для использования в миграции ---
protection_level_enum = sa.Enum('none', 'basic', 'full', name='protectionlevel')


def upgrade() -> None:
    # --- ИСПРАВЛЕНИЕ 2: Создаем ENUM тип в базе данных ПЕРЕД созданием колонки ---
    protection_level_enum.create(op.get_bind(), checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    # (Здесь Alembic сгенерировал op.add_column, op.drop_column и т.д.)
    # Оставьте этот сгенерированный код как есть.
    # Пример того, что там может быть:
    op.add_column('orders_services', sa.Column('protection_level', sa.Enum('none', 'basic', 'full', name='protectionlevel'), nullable=False))
    op.add_column('orders_services', sa.Column('comment', sa.Text(), nullable=True))
    op.drop_column('orders', 'parameters_and_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Здесь Alembic сгенерировал код для отката)
    # Оставьте этот сгенерированный код как есть.
    # Пример:
    op.add_column('orders', sa.Column('parameters_and_comments', sa.JSON(), autoincrement=False, nullable=True))
    op.drop_column('orders_services', 'comment')
    op.drop_column('orders_services', 'protection_level')
    # ### end Alembic commands ###
    
    # --- ИСПРАВЛЕНИЕ 3: Удаляем ENUM тип из базы данных ПОСЛЕ удаления колонки ---
    protection_level_enum.drop(op.get_bind(), checkfirst=False)